<?php
if(sizeof($travels) > 0){

    $paginator = '';
    if ($this->pages > 1) {
        $paginator .= '
        <!-- Pagination -->
        <ul class="actions pagination">';
        if ($this->page > 1) {
            $paginator .= '<li><a href="' . $this->url((!preg_match('/^travels\//', $_SERVER['REQUEST_URI'])?'home':'travels'), ['action' => 'index', 'page' => ($this->page - 1)]) . '" class="button big previous">' . $this->translate('Previous Page') . '</a></li>';
        }
        if (($this->page + 1) <= $this->pages) {
            $paginator .= '<li><a href="' . $this->url((!preg_match('/^travels\//', $_SERVER['REQUEST_URI'])?'home':'travels'), ['action' => 'index', 'page' => ($this->page + 1)]) . '" class="button big next">' . $this->translate('Next Page') . '</a></li>';
        }
        $paginator .= '</ul>';
    }

    foreach($travels as $travel) {
        //date('F d, Y', $date)
        $date = strtotime($travel['date']);
        echo '
        <article class="post">
            <header>
                <div class="title">
                    <h2><a href="' . $this->url('travels_view', ['action' => 'view', 'url' => $travel['url']]) . '">' . $travel['title'] . '</a></h2>
                    <p>' . $travel['subtitle'] . '</p>
                </div>
                <div class="meta">
                    <time class="published" datetime="' . date('Y-m-d', $date) . '">' . strftime('%a, %b %e, %Y', $date) . '</time>
                    <a href="' . $this->url('users', ['action' => 'view', 'id' => $travel['user_id']]) . '" class="author"><span class="name" style="font-size: 0.8em;">' . $travel['full_name'] . '</span><img src="/img/users/' . $travel['user_id'] . '/small_' . $travel['photo'] . '" alt="' . $travel['full_name'] . '" /></a>
                </div>
            </header>';
            if ($travel['image'] != '') {
                echo '<a href="' . $this->url('travels_view', ['action' => 'view', 'url' => $travel['url']]) . '" class="image featured"><img src="/img/travels/' . $travel['article_id'] . '/' . $travel['image'] . '" alt="' . $travel['title'] . '" /></a>';
            }
            echo ($travel['announce'] != ''?$travel['announce'].'<br /><br />':'').'
            <footer>
                <ul class="actions">
                    <li><a href="'.$this->url('travels_view', ['action' => 'view', 'url' => $travel['url']]).'" class="button big">'.$this->translate('Continue Reading').'</a></li>
                </ul>
                <!--
                <ul class="stats">
                    <li><a href="#">General</a></li>
                    <li><a href="#" class="icon fa-heart">28</a></li>
                    <li><a href="#" class="icon fa-comment">128</a></li>
                </ul>
                -->
            </footer>
        </article>';
    }

    echo $paginator;
}

//// Posts List
//$date = strtotime($travel['date']);
//echo '
//<section>
//    <ul class="posts">';
//        foreach($travels as $travel){
//            echo '
//            <li>
//                <article>
//                    <header>
//                        <h3><a href="'.$this->url('travels_view', ['action' => 'view', 'url' => $travel['url']]).'">'.$travel['title'].'</a></h3>
//                        <time class="published" datetime="'.date('Y-m-d', $date).'">'.date('F d, Y', $date).'</time>
//                    </header>
//                    <a href="'.$this->url('travels_view', ['action' => 'view', 'url' => $travel['url']]).'" class="image"><img src="'.$travel['image'].'" alt="'.$travel['title'].'" /></a>
//                </article
//            </li>';
//        }
//    echo '
//    </ul>
//</section>';

//<!-- Post -->
//<!--
//<article class="post">
//    <header>
//        <div class="title">
//            <h2><a href="#">Magna sed adipiscing</a></h2>
//            <p>Lorem ipsum dolor amet nullam consequat etiam feugiat</p>
//        </div>
//        <div class="meta">
//            <time class="published" datetime="2015-11-01">November 1, 2015</time>
//            <a href="#" class="author"><span class="name">Jane Doe</span><img src="/templates/future-imperfect/images/avatar.jpg" alt="" /></a>
//        </div>
//    </header>
//    <span class="image featured"><img src="/templates/future-imperfect/images/pic01.jpg" alt="" /></span>
//    <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
//    <p>Nunc quis dui scelerisque, scelerisque urna ut, dapibus orci. Sed vitae condimentum lectus, ut imperdiet quam. Maecenas in justo ut nulla aliquam sodales vel at ligula. Sed blandit diam odio, sed fringilla lectus molestie sit amet. Praesent eu tortor viverra lorem mattis pulvinar feugiat in turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ullamcorper tellus sit amet mattis dignissim. Phasellus ut metus ligula. Curabitur nec leo turpis. Ut gravida purus quis erat pretium, sed pellentesque massa elementum. Fusce vestibulum porta augue, at mattis justo. Integer sed sapien fringilla, dapibus risus id, faucibus ante. Pellentesque mattis nunc sit amet tortor pellentesque, non placerat neque viverra. </p>
//    <footer>
//        <ul class="stats">
//            <li><a href="#">General</a></li>
//            <li><a href="#" class="icon fa-heart">28</a></li>
//            <li><a href="#" class="icon fa-comment">128</a></li>
//        </ul>
//    </footer>
//</article>
//-->