<?php
$this->headTitle($this->member[0]['name']);

echo '
<style>
    .box {
        padding: 0.5em !important;
    }
    header.major h2 {
        top: -0.55em !important;
    }
    h2 {
        font-size: 2em !important;
    }
    header.major {
        border-top: none !important;
    }
</style>';

echo '<h2>'.$this->member[0]['name'].'</h2>';
echo '<a href="'.$this->url('family-gallery', ['action' => 'index']).'">&larr; back</a>';
echo '<br /><br />';

if(isset($this->years) and sizeof($this->years) > 0) {
    foreach ($this->years as $year) {
        echo '
        <section>
            <h2>'.$year.'</h2>';

            echo '
            <ul class="actions">';
                foreach($this->months[$year] as $month){
                    echo '<li><a class="button fit" href="'.$this->url('family-gallery', ['action' => 'view', 'member_id' => $this->member_id, 'year' => $year, 'month' => $month]).'" class="button small">'.date('F', strtotime($year.'-'.$month.'-01')).'<span style="color: darkgray;"> / '.$year.'</a></li>';
                }
            echo'
            </ul>';

//            echo '
//            <div class="row">';
//            foreach($this->months[$year] as $month){
//                echo '
//                <div class="4u 12u(mobile)">
//                    <section class="box" style="text-align: center; font-size: 1em;">
//                        <header>
//                            <a href="'.$this->url('family-gallery', ['action' => 'view', 'member_id' => $this->member_id, 'year' => $year, 'month' => $month]).'"
//                               style="text-decoration: none;"><h3>'.date('F', strtotime($year.'-'.$month.'-01')).'<span style="color: darkgray;"> / '.$year.'</span></h3></a>
//                        </header>
//                    </section>
//                </div>';
//            }
//            echo'
//            </div>';
        echo '
        </section>';
    }
}
