<?php
$this->headTitle($this->member[0]['name'].' / '.$this->year.' / '.date('F', strtotime($this->year.'-'.$this->month.'-01')));

//if(isset($this->photos) and sizeof($this->photos) > 0) {
//    foreach ($this->photos as $photo) {
//        echo '
//        <article class="thumb">
//            <a class="image" href="/img/family-gallery-member/'.$this->member[0]['id'].'/photos/'.$this->gallery['year'].'/'.($this->gallery['month'] < 10?'0':'').$this->gallery['month'].'/'.$photo['path'].'">
//                <img src="/img/family-gallery-member/'.$this->member[0]['id'].'/photos/'.$this->gallery['year'].'/'.($this->gallery['month'] < 10?'0':'').$this->gallery['month'].'/preview_'.$photo['path'].'" alt="" /></a>
//            <h2></h2>
//            <p>'.($photo['sortby'] + 1).' / '.sizeof($this->photos).'</p>
//        </article>';
//    }
//}

echo '<header id="header">
    <h1>'.$this->member[0]['name'].'</h1>
    <p>'.$this->year.' / '.date('F', strtotime($this->year.'-'.$this->month.'-01')).'<br />
    <a href="'.$this->url('family-gallery', ['action' => 'view', 'member_id' => $this->member_id]).'">&larr; back</a></p>
</header>';

if(isset($this->photos) and sizeof($this->photos) > 0) {
    echo '<section id="thumbnails">';
        foreach ($this->photos as $photo) {
            echo '
            <article>
                <a class="thumbnail" href="/img/family-gallery-member/'.$this->member[0]['id'].'/photos/'.$this->gallery['year'].'/'.($this->gallery['month'] < 10?'0':'').$this->gallery['month'].'/'.$photo['path'].'">
                    <img src="/img/family-gallery-member/'.$this->member[0]['id'].'/photos/'.$this->gallery['year'].'/'.($this->gallery['month'] < 10?'0':'').$this->gallery['month'].'/preview_'.$photo['path'].'" alt="" /></a>
                <h2></h2>
                <p>'.($photo['sortby'] + 1).' / '.sizeof($this->photos).'</p>
            </article>';
        }
    echo '</section>';
}