<?php
$this->headTitle($this->translate('Edit Travels'));

$this->pageBreadcrumbs()->setHeader($this->travel['txt'][$_SESSION['locale']]['title']);
$this->pageBreadcrumbs()->setItems([
    $this->translate('Travels') => $this->url('travels'),
    $this->translate('Edit Travels') => $this->url('travels_admin'),
    $this->translate('Add Travel') => $this->url('travels_admin', ['action' => 'add']),
]);

$this->form->get('url')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>$this->translate('Url'),
    'value' => $this->travel['url'],
    'style' => 'width: 80%;',
]);

$this->form->get('date')->setAttributes([
    'class'=>'form-control',
    'id'=>'date',
    'placeholder'=>$this->translate('Date'),
    'value' => date('d.m.Y', strtotime($this->travel['date'])),
    'size'  => 7,
]);

$this->form->get('image')->setAttributes([
    'class'=>'form-control',
    'style' => 'width: 80%;'
]);

$this->form->get('status')->setAttributes([
    'class'=>'form-control',
    'value' => $this->travel['status']
]);

$this->form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue($this->translate('Save'));

$this->form->prepare();
?>

<h3><?= $this->travel['txt'][$_SESSION['locale']]['title']; ?></h3>
<small style="color: grey;"><a href="<?= $this->url('travels_admin'); ?>">&larr; <?= $this->translate('Back to Travel'); ?></a> / <?= $this->translate('Travel Editing'); ?></small>
<br /><br />

<script type="text/javascript" src="/js/jquery-1.7.1.js"></script>
<script type="text/javascript" src="/js/jquery-ui.js"></script>
<link rel="stylesheet" href="/css/bootstrap-datepicker.css">

<style type="text/css" media="screen">
    .btn.jumbo {
        font-size: 20px;
        font-weight: normal;
        padding: 14px 24px;
        margin-right: 10px;
        -webkit-border-radius: 6px;
        -moz-border-radius: 6px;
        border-radius: 6px;
    }
</style>

<script type="text/javascript">
    function hideView(id) {
        if($('#div_' + id).css('display') == 'none'){
            $('#div_' + id).show();
        } else {
            $('#div_' + id).hide();
        }

        return false;
    }

    function deleteImage(id, url) {
        $.ajax({
            type: "DELETE",
            url: url,
            dataType : "html",
            data: ({ }),
            async: false,
            success: function (data){
                $('#image_' + id).hide();
            }
        });

        return false;
    }
</script>

<br />

<div>

    <?= $this->form()->openTag($this->form); ?>

    <div style="float: right;">
        <?= $this->formElement($this->form->get('submit')); ?>
    </div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#main-info" aria-controls="main-info" role="tab" data-toggle="tab"><?= $this->translate('Main Info'); ?></a></li>
        <?php foreach ($this->langs as $lang): ?>
            <li role="presentation"><a href="#<?= $lang['locale']; ?>" aria-controls="<?= $lang['locale']; ?>" role="tab" data-toggle="tab"><?= ($lang['locale'] == 'ru_RU'?$this->translate('Russian'):$this->translate('English')); ?></a></li>
        <?php endforeach; ?>
        <li role="presentation"><a href="#images" aria-controls="images" role="tab" data-toggle="tab"><?= $this->translate('Images'); ?></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="main-info" style="border-left: 1px solid #ddd;
            border-bottom: 1px solid #ddd;
            border-right: 1px solid #ddd;
            padding: 15px;">
            <div class="form-group">
                <?= $this->formLabel($this->form->get('url')); ?>
                <?= $this->formElement($this->form->get('url')); ?>
                <?= $this->formElementErrors($this->form->get('url')); ?>
                <a href="<?= $this->url('travels_view', ['url' => $this->travel['url']]); ?>?preview=1" target="_blank<?= $this->travel['travel_id']; ?>"><?= $this->translate('Preview'); ?></a>
            </div>
            <br />
            <div class="form-group">
                <?= $this->formLabel($this->form->get('date')); ?>
                <input type='text' class="form-control" name="date" id="datepicker" value="" />
                <script>
                    $(function() {
                        $( "#datepicker" ).datepicker();
                        $( "#datepicker" ).datepicker( "option", "dateFormat", "dd.mm.yy" );
                        $( "#datepicker" ).val("<?= date('d.m.Y', strtotime($this->travel['date'])); ?>");
                    });
                </script>
                <?= $this->formElementErrors($this->form->get('date')); ?>
                <?php /* ?>
                <div class="container">
                    <div class="row">
                        <div class='col-sm-6' style="padding-left: 0 !important;">
                            <div class="form-group">
                                <?= $this->formLabel($this->form->get('date')); ?>
                                <div class='input-group date' id='datetimepicker2'>
                                    <?//= $this->formElement($this->form->get('date')); ?>
                                    <input type='text' class="form-control" name="date" value="<?= date('Y-m-d H:i', strtotime($this->travel['date'])); ?>" />
                                    <span class="input-group-addon" style="height: 20px !important;">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                                <?= $this->formElementErrors($this->form->get('date')); ?>
                            </div>
                        </div>
                        <script type="text/javascript">
                            $(function () {
                                $('#datetimepicker2').datetimepicker({
                                    locale: 'ru'
                                });
                            });
                        </script>
                    </div>
                </div>
                <?php */ ?>
            </div>
            <br />
            <div class="form-group">
                <?= $this->formLabel($this->form->get('image')); ?>
                <?= $this->formElement($this->form->get('image')); ?>
                <?= $this->formElementErrors($this->form->get('image')); ?>
                <?= ($travel['image'] != ''?'<br /><img src="/img/travels/'.$this->travel['travel_id'].'/'.$this->travel['image'].'" width="100%">':'') ?>
            </div>
            <br />
            <div class="form-group">
                <?= $this->formLabel($this->form->get('status')); ?>
                <?= $this->formElement($this->form->get('status')); ?>
                <?= $this->formElementErrors($this->form->get('status')); ?>
            </div>
        </div>
        <?php foreach ($this->langs as $lang): ?>
            <div role="tabpanel" class="tab-pane" id="<?= $lang['locale']; ?>" style="border-left: 1px solid #ddd;
                border-bottom: 1px solid #ddd;
                border-right: 1px solid #ddd;
                padding: 15px;">
                <h3><?= $this->translate('Title'); ?></h3>
                <input type="text" class="form-control" name="<?= $lang['locale']; ?>[title]" style="width: 60%;" placeholder="<?= $this->translate('Title'); ?>" value="<?= $this->travel['txt'][$lang['locale']]['title']; ?>">
                <br />
                <h3><?= $this->translate('Subtitle'); ?></h3>
                <input type="text" class="form-control" name="<?= $lang['locale']; ?>[subtitle]" style="width: 60%;" placeholder="<?= $this->translate('Subtitle'); ?>" value="<?= $this->travel['txt'][$lang['locale']]['subtitle']; ?>">
                <br />
                <h3><?= $this->translate('Announce'); ?></h3>
                <textarea class="form-control" style="width: 100%;" name="<?= $lang['locale']; ?>[announce]" cols="140" rows="3"><?= $this->travel['txt'][$lang['locale']]['announce']; ?></textarea>
                <br />
                <h3><?= $this->translate('Text'); ?></h3>
                <textarea class="form-control" style="width: 100%;" id="text_<?= $lang['locale']; ?>" name="<?= $lang['locale']; ?>[text]" rows="60"><?= $this->travel['txt'][$lang['locale']]['text']; ?></textarea>
            </div>
        <?php endforeach; ?>

        <?= $this->form()->closeTag(); ?>

        <div role="tabpanel" class="tab-pane" id="images" style="padding: 15px;">

            <link rel="stylesheet" href="/js/jquery-file-upload-9.14.2/css/jquery.fileupload.css">
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/vendor/jquery.ui.widget.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/load-image.all.min.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/canvas-to-blob.min.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/jquery.iframe-transport.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/jquery.fileupload.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/jquery.fileupload-process.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/jquery.fileupload-image.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/jquery.fileupload-audio.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/jquery.fileupload-video.js"></script>
            <script type="text/javascript" src="/js/jquery-file-upload-9.14.2/js/jquery.fileupload-validate.js"></script>

            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span><?= $this->translate('Add files...'); ?></span>
                <!-- The file input field used as target for the file upload widget -->
                <input id="fileupload" type="file" name="files[]" multiple>
            </span>

            <br /><br />

            <!-- The global progress bar -->
            <div id="progress" class="progress">
                <div class="progress-bar progress-bar-success"></div>
            </div>

            <!-- The container for the uploaded files -->
            <div id="files" class="files">
                <?php
                if (isset($this->images) and sizeof($this->images) > 0) {
                ?>
                    <?php $col = 0;?>
                    <?php foreach ($this->images as $image): ?>
                        <div id="image_<?= $col; ?>" style="clear: both; margin-bottom: 20px;">
                            <img src="/img/travels/<?= $this->travel['travel_id']; ?>/files/thumbnail/<?= $image; ?>">
                            <div style="margin-top: 5px;">
                            <button type="button" class="btn btn-info btn-xs" onclick="hideView(<?php $rand = rand(1, 10000); echo $rand; ?>);">
                                <i class="glyphicon glyphicon-eye-open"></i>
                                <span><?= $this->translate('View/Hide'); ?></span>
                            </button>
                            <button type="button" class="btn btn-danger delete btn-xs" onclick="if(confirm('<?= $this->translate('Do you really want to delete this image?'); ?>')){deleteImage(<?= $col; ?>, '/img/uploads/index.php?travel_id=<?= $this->travel['travel_id']; ?>&file=<?= $image; ?>');}">
                                <i class="glyphicon glyphicon-trash"></i>
                                <span><?= $this->translate('Delete'); ?></span>
                            </button>
                            </div>
                            <div class="form-group form-group-sm" id="div_<?= $rand; ?>" style="display: none;">
                                <br />
                                <b><?= $this->translate('Link'); ?></b>
                                <input class="form-control" style="width: 80%;" value="/img/travels/<?= $this->travel['travel_id']; ?>/files/<?= $image; ?>" type="text">
                                <b><?= $this->translate('Image Fit'); ?></b>
                                <input class="form-control" style="width: 80%;" value="&lt;div class=&quot;12u$&quot;&gt;&lt;span class=&quot;image fit&quot;&gt;&lt;img src=&quot;/img/travels/<?= $this->travel['travel_id']; ?>/files/<?= $image; ?>&quot; alt=&quot;&quot;&gt;&lt;/span&gt;&lt;/div&gt;" type="text">
                                <b><?= $this->translate('Image Left'); ?></b>
                                <input class="form-control" style="width: 80%;" value="&lt;span class=&quot;image left&quot; style=&quot;&quot;&gt;&lt;img src=&quot;/img/travels/<?= $this->travel['travel_id']; ?>/files/<?= $image; ?>&quot; alt=&quot;&quot;&gt;&lt;/span&gt;" type="text">
                                <b><?= $this->translate('Image Right'); ?></b>
                                <input class="form-control" style="width: 80%;" value="&lt;span class=&quot;image right&quot; style=&quot;&quot;&gt;&lt;img src=&quot;/img/travels/<?= $this->travel['travel_id']; ?>/files/<?= $image; ?>&quot; alt=&quot;&quot;&gt;&lt;/span&gt;" type="text">
                                <br />
                            </div>
                        </div>
                        <?php $col++; ?>
                    <?php endforeach; ?>
                <?php
                }
                ?>
            </div>

            <script type="text/javascript">
                /*jslint unparam: true, regexp: true */
                /*global window, $ */
                $(function () {
                    'use strict';
                    // Change this to the location of your server-side upload handler:
                    var url = '/img/uploads/index.php?travel_id=<?= $this->travel['travel_id']; ?>',
                        uploadButton = $('<button/>')
                            .addClass('btn btn-primary')
                            .prop('type', 'button')
                            .prop('disabled', true)
                            .text('Processing...')
                            .on('click', function () {
                                var $this = $(this),
                                    data = $this.data();
                                $this
                                    .off('click')
                                    .text('Abort')
                                    .on('click', function () {
                                        $this.remove();
                                        data.abort();
                                    });
                                data.submit().always(function () {
                                    $this.remove();
                                });
                            });
                    $('#fileupload').fileupload({
                        url: url,
                        dataType: 'json',
                        autoUpload: false,
                        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
                        maxFileSize: 8192000,
                        // Enable image resizing, except for Android and Opera,
                        // which actually support image resizing, but fail to
                        // send Blob objects via XHR requests:
                        disableImageResize: /Android(?!.*Chrome)|Opera/
                            .test(window.navigator.userAgent),
                        previewMaxWidth: 120,
                        previewMaxHeight: 120,
                        previewCrop: true,
                    }).on('fileuploadadd', function (e, data) {
                        data.context = $('<div/>').appendTo('#files');
                        $.each(data.files, function (index, file) {
                            var node = $('<p/>')
                                .append($('<span/>').text(file.name));
                            if (!index) {
                                node
                                    .append('<br>')
                                    .append(uploadButton.clone(true).data(data));
                            }
                            node.appendTo(data.context);
                        });
                    }).on('fileuploadprocessalways', function (e, data) {
                        var index = data.index,
                            file = data.files[index],
                            node = $(data.context.children()[index]);
                        if (file.preview) {
                            node
                                .prepend('<br>')
                                .prepend(file.preview);
                        }
                        if (file.error) {
                            node
                                .append('<br>')
                                .append($('<span class="text-danger"/>').text(file.error));
                        }
                        if (index + 1 === data.files.length) {
                            data.context.find('button')
                                .text('Upload')
                                .prop('type', 'button')
                                .prop('disabled', !!data.files.error);
                        }
                    }).on('fileuploadprogressall', function (e, data) {
                        var progress = parseInt(data.loaded / data.total * 100, 10);
                        $('#progress .progress-bar').css(
                            'width',
                            progress + '%'
                        );
                    }).on('fileuploaddone', function (e, data) {
                        $.each(data.result.files, function (index, file) {
                            if (file.url) {
//                                var link = $('<a>')
//                                    .attr('target', '_blank')
//                                    .prop('href', file.url);
//                                $(data.context.children()[index])
//                                    .wrap(link);
                                $(data.context.children()[index])
                                    .append('<div class="form-group form-group-sm"><br /><img src="/img/travels/<?= $this->travel['travel_id']; ?>/files/thumbnail/' + file.name + '"><br /><br /><b><?= $this->translate('Link'); ?></b><br /><input type="text" class="form-control" style="width: 80%;" value="/img/travels/<?= $this->travel['travel_id']; ?>/files/' + file.name + '">' +
                                        '<br /><b><?= $this->translate('Image Fit'); ?></b><input type="text" class="form-control" style="width: 80%;" value="<div class=&quot;12u$&quot;><span class=&quot;image fit&quot;><img src=&quot;/img/travels/<?= $this->travel['travel_id']; ?>/files/' + file.name + '&quot; alt=&quot;&quot;></span></div>">' +
                                        '<b><?= $this->translate('Image Left'); ?></b><input type="text" class="form-control" style="width: 80%;" value="<span class=&quot;image left&quot; style=&quot;&quot;><img src=&quot;/img/travels/<?= $this->travel['travel_id']; ?>/files/' + file.name + '&quot; alt=&quot;&quot;></span>">' +
                                        '<b><?= $this->translate('Image Right'); ?></b><input type="text" class="form-control" style="width: 80%;" value="<span class=&quot;image right&quot; style=&quot;&quot;><img src=&quot;/img/travels/<?= $this->travel['travel_id']; ?>/files/' + file.name + '&quot; alt=&quot;&quot;></span>"><br /><br /></div>');
                            } else if (file.error) {
                                var error = $('<span class="text-danger"/>').text(file.error);
                                $(data.context.children()[index])
                                    .append('<br>')
                                    .append(error);
                            }
                        });
                    }).on('fileuploadfail', function (e, data) {
                        $.each(data.files, function (index) {
                            var error = $('<span class="text-danger"/>').text('File upload failed.');
                            $(data.context.children()[index])
                                .append('<br>')
                                .append(error);
                        });
                    }).prop('disabled', !$.support.fileInput)
                        .parent().addClass($.support.fileInput ? undefined : 'disabled');
                });
            </script>
        </div>
    </div>
</div>

<br /><br />