<?php
$this->headTitle('Edit User');

$this->mainMenu()->setActiveItemId('users');

//$this->pageBreadcrumbs()->setItems([
//    'Home'=>$this->url('home'),
//    'Manage Users'=>$this->url('users'),
//    'Edit User'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
//]);

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com',
    'value' => $user['email'],
    'size'  => 70,
]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe',
    'value' => $user['full_name'],
    'size'  => 80,
]);

$form->get('photo')->setAttributes([
    'class'=>'form-control',
]);

$form->get('status')->setAttributes([
    'class'=>'form-control',
]);

$form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue('Save');

$form->prepare();
?>

<h1>Edit User</h1>
<a href="<?= $this->url('users', ['action' => 'view', 'id' => $user['id']]) ?>">View</a><br /><br />

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('photo')); ?>
            <?= $this->formElement($form->get('photo')); ?>
            <?= $this->formElementErrors($form->get('photo')); ?>
            <?= ($user['photo'] != ''?'<br /><img src="/img/users/'.$this->user['id'].'/'.$user['photo'].'">':'') ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>
        <br />
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<?php
#$r = $this->user->getRoles();
#echo '<pre>'; print_r($r); echo '</pre>';
?>
