<?php
$this->headTitle($this->translate('Edit User'));

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')=>$this->url('home'),
    $this->translate('Manage Users')=>$this->url('users'),
    $this->translate('Edit User')=>$this->url('users', ['action'=>'edit', 'id'=>$user['id']])
]);

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com',
    'value' => $user['email'],
    'size'  => 70,
]);

foreach ($_SESSION['langs'] as $lang) {
    $form->get('full_name_'.$lang['locale'])->setAttributes([
        'class' => 'form-control',
        'placeholder' => $this->translate('Full Name'),
        'value' => $user['txt'][$lang['locale']]['full_name'],
        'size' => 80,
    ]);
}

$form->get('photo')->setAttributes([
    'class'=>'form-control',
]);

$form->get('status')->setAttributes([
    'class'=>'form-control',
]);

$form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue('Save');

$form->prepare();
?>

<h1><?= $this->translate('Edit User'); ?></h1>
<a href="<?= $this->url('users', ['action' => 'view', 'id' => $user['id']]) ?>"><?= $this->translate('View'); ?></a> |
<a href="<?= $this->url('users', ['action' => 'change-password', 'id' => $user['id']]) ?>"><?= $this->translate('Change Password'); ?></a>
<br /><br />

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>
        <br />
        <?= $this->formLabel($form->get('full_name_'.$lang['locale'])); ?>

        <div class="form-group">
            <?php foreach ($_SESSION['langs'] as $lang):?>
                <?= '<small>'.$lang['name'].'</small>'; ?>
                <?= $this->formElement($form->get('full_name_'.$lang['locale'])); ?>
                <?= $this->formElementErrors($form->get('full_name_'.$lang['locale'])); ?>
                <br />
            <?php endforeach; ?>
        </div>
        <br />
        <div class="form-group">
            <?= $this->formLabel($form->get('photo')); ?>
            <?= $this->formElement($form->get('photo')); ?>
            <?= $this->formElementErrors($form->get('photo')); ?>
            <?= ($user['photo'] != ''?'<br /><img src="/img/users/'.$this->user['id'].'/'.$this->user['photo'].'">':'') ?>
        </div>
        <br />
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>
        <br />
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<?php
#$r = $this->user->getRoles();
#echo '<pre>'; print_r($r); echo '</pre>';
?>
