<?php
$this->headTitle($this->translate('Users'));

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')=>$this->url('home'),
    $this->translate('Manage Users')=>$this->url('users'),
]);
?>

<h1><?= $this->translate('Manage Users'); ?></h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th><?= $this->translate('Full Name'); ?></th>
        <th><?= $this->translate('Date Created'); ?></th>
        <th><?= $this->translate('Status'); ?></th>
        <th><?= $this->translate('Actions'); ?></th>
    </tr>

    <?php foreach ($users as $user): ?>

        <tr>
            <td><?= $this->escapeHtml($user['id']); ?></td>
            <td>
                <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user['id']]); ?>">
                    <?= $this->escapeHtml($user['email']); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($user['full_name']); ?></a>
            </td>
            <td><?= $this->escapeHtml($user['date_created']); ?></td>
            <td><?= $this->escapeHtml($user['status']); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('users', ['action'=>'edit', 'id'=>$user['id']]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> <?= $this->translate('Edit'); ?>
                </a>
                |
                <a class="btn btn-default" href="<?= $this->url('users', ['action'=>'change-password', 'id'=>$user['id']]); ?>">
                    <span class="glyphicon glyphicon-asterisk"></span> <?= $this->translate('Change Password'); ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>
