<?php
$this->headTitle($this->translate('User Register'));

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')=>$this->url('home'),
    $this->translate('Manage Users')=>$this->url('users'),
    $this->translate('Add User')=>$this->url('users', ['action'=>'add'])
]);

$form->get('email')->setAttributes(['class'=>'form-control', 'placeholder'=>'name@example.com']);
$form->get('full_name')->setAttributes(['class'=>'form-control', 'placeholder'=>'John Doe']);
//$form->get('status')->setAttributes(['class'=>'form-control']);
//$form->get('password')->setAttributes(['class'=>'form-control']);
//$form->get('confirm_password')->setAttributes(['class'=>'form-control']);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1><?= $this->translate('User Register'); ?></h1>

<p><?= $this->translate('Please fill out the following form and click the <i>Register</i> button.'); ?></p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>
        </div>

        <?php /* ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>
        <?php */ ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
