<section id="intro">
    <?php
    if(isset($user) and sizeof($user) > 0){
        echo '<a href="'.$this->url('users', ['action' => 'view', 'id' => $user['id']]).'" class="logo"><img src="/img/users/'.$user['id'].'/'.$user['photo'].'" alt="" /></a>';
    }
    ?>
    <header>
        <h2><?= $this->translate('Our life'); ?></h2>
        <p><?= $this->translate('Our life, our family, our travels and etc.'); ?></a></p>
    </header>
</section>