<?php
$this->headTitle($this->translate('About'));

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')=>$this->url('home'),
    $this->translate('About')=>$this->url('about'),
]);
?>

<h1><?= $this->translate('About'); ?></h1>
<p><?= $this->translate('Application name'); ?>: <?= $this->escapeHtml($appName) ?></p>
<p><?= $this->translate('Application description'); ?>: <?= $this->escapeHtml($appDescription) ?></p>
