<?php
$this->headTitle($this->translate('About'));

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')=>$this->url('home'),
    $this->translate('About')=>$this->url('about'),
]);
?>

<h1><?= $this->translate('About'); ?></h1>

<?= $this->form()->openTag($this->form); ?>
<?= $this->formLabel($this->form->get('pay_amount')); ?>
<?= $this->formElement($this->form->get('pay_amount')); ?>
<?= $this->formElementErrors($this->form->get('pay_amount')); ?>
<br />
<?= $this->formElement($this->form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
<?php
if (isset($this->pay_result) and sizeof($this->pay_result) > 0) {
    echo $this->translate('Pay Amount') . ': ' . $this->pay_amount . '<br />';
    foreach ($this->pay_result as $row) {
        echo $row . '<br />';
    }
    echo '<a href="'.$this->url('about').'">'.$this->translate('One more time').'</a>';
}
