<?php
$this->headTitle($this->translate('Settings'));

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')=>$this->url('home'),
    $this->translate('Settings')=>$this->url('application', ['action'=>'settings']),
]);
?>

<h2><?= $this->translate('Settings'); ?></h2>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th><?= $this->translate('Full Name'); ?>:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th><?= $this->translate('Date Created'); ?>:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>
