<!DOCTYPE HTML>
<html>
<head>
    <?= $this->headTitle('Our life')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="/templates/dopetrope/assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="/templates/dopetrope/assets/css/main.css" />
    <!--[if lte IE 8]><link rel="stylesheet" href="/templates/dopetrope/assets/css/ie8.css" /><![endif]-->
</head>
<body class="homepage">
<div id="page-wrapper">

    <!-- Header -->
    <div id="header-wrapper">
        <div id="header">
            <!-- Logo -->
            <h1><a href="/">Family Gallery</a></h1>

        </div>
    </div>

    <!-- Main -->
    <div id="main-wrapper">
        <div class="container">

            <div class="row">
                <div class="12u">
                    <?= $this->content ?>
                </div>
            </div>

        </div>
    </div>

</div>

<!-- Scripts -->
<script src="/templates/dopetrope/assets/js/jquery.min.js"></script>
<script src="/templates/dopetrope/assets/js/jquery.dropotron.min.js"></script>
<script src="/templates/dopetrope/assets/js/skel.min.js"></script>
<script src="/templates/dopetrope/assets/js/skel-viewport.min.js"></script>
<script src="/templates/dopetrope/assets/js/util.js"></script>
<!--[if lte IE 8]><script src="/templates/dopetrope/assets/js/ie/respond.min.js"></script><![endif]-->
<script src="/templates/dopetrope/assets/js/main.js"></script>

</body>
</html>