<!DOCTYPE HTML>
<html>
	<head>
		<?= $this->headTitle('Our life')->setSeparator(' - ')->setAutoEscape(false) ?>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="/templates/lens/assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="/templates/lens/assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="/templates/lens/assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="/templates/lens/assets/css/ie9.css" /><![endif]-->
		<noscript><link rel="stylesheet" href="/templates/lens/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-loading-0 is-loading-1 is-loading-2">

		<!-- Main -->
		<div id="main">

			<?= $this->content ?>

		</div>

		<!-- Scripts -->
		<script src="/templates/lens/assets/js/jquery.min.js"></script>
		<script src="/templates/lens/assets/js/skel.min.js"></script>
		<!--[if lte IE 8]><script src="/templates/lens/assets/js/ie/respond.min.js"></script><![endif]-->
		<script src="/templates/lens/assets/js/main.js"></script>

	</body>
</html>